### ISSUE TITLE
Resize => Unable to cast object of type 'System.Byte[]' to type 'System.Byte'.

### ISSUE THREAD

**Issue by vinhhrv** [JimBobSquarePants/ImageSharp#160] opened 2017-03-29 05:00 UTC
### Prerequisites

- [x ] I have written a descriptive issue title
- [x ] I have verified that I am running the latest version of ImageSharp
- [x ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x ] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Resize Image Exception 
Unable to cast object of type 'System.Byte[]' to type 'System.Byte'.

### Steps to Reproduce

var outStream = new MemoryStream(8000);

`using (var file = File.OpenRead("files/jpg_bug.jpg"))`
 `{ `
 `     var image = Image.Load(file);`
`   ResizeOptions opt = new ResizeOptions();`
`      opt.Mode = ResizeMode.Max;`
 `                   opt.Size = new ResizeInfo(new Size(100,100));`
`                    image.Resize(opt)`
`                         .Save(outStream);`
`}`

Attach file

### System Configuration

- ImageSharp version: 1.0.0-alpha5-00046
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): win10
- .NET Framework version: netcoreapp
- Additional information:

![jpg_bug_2](https://cloud.githubusercontent.com/assets/769541/24439165/b8687014-1476-11e7-8804-1021f38bfaa8.jpg)

**Comment by vinhhrv** [comment] 2017-03-29 05:01
sori, dupplicate 
https://github.com/JimBobSquarePants/ImageSharp/issues/132

**Comment by antonfirsov** [comment] 2017-03-29 23:36
@vinhhrv are you sure you are using the latest version? this should be fixed now.

**Comment by antonfirsov** [comment] 2017-03-30 00:30
@vinhhrv sorry, I made & deleted a comment by mistake! I thought this was duplicate of 146. 

#132 is not fixed yet, definitely a duplicate here :)

**Closed** 2017-03-30 00:30 UTC
