### ISSUE TITLE
Image.Load with interlaced PNG files: System.ArgumentOutOfRangeException : Non-negative number required. Parameter name: count

### ISSUE THREAD

**Issue by srudenko** [JimBobSquarePants/ImageSharp#191] opened 2017-04-26 17:05 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Exception happens when files loaded from stream. It only happens with some interlaced PNG files, particularly with the following 2 files
![invalidpngwithinterlacing](https://cloud.githubusercontent.com/assets/576927/25446457/895306b0-2aa9-11e7-8a5a-c03330d0eca8.png)
![91c3ae_fdc3323aeacf4744b1ff1418c8f100d2](https://cloud.githubusercontent.com/assets/576927/25447459/30920216-2aad-11e7-9236-9ed2b5208499.png)

I have tested the same code with interlaced PNG from your repository [plash-interlaced.png](https://github.com/JimBobSquarePants/ImageSharp/blob/master/tests/ImageSharp.Tests/TestImages/Formats/Png/splash-interlaced.png) and it was successfully loaded.

### Steps to Reproduce

>                    using (var fileStream = File.OpenWrite(filePath))
>                     {
>                               input.Seek(0, SeekOrigin.Begin);> 
>                               var image = Image.Load(input);
>                     }

Exception is:

`System.ArgumentOutOfRangeException : Non-negative number required.
Parameter name: count
   at System.IO.Win32FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.DeflateStream.Read(Byte[] array, Int32 offset, Int32 count)
   at ImageSharp.Formats.ZlibInflateStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at ImageSharp.Formats.PngDecoderCore.DecodeInterlacedPixelData[TPixel](Stream compressedStream, PixelAccessor1 pixels)
   at ImageSharp.Formats.PngDecoderCore.Decode[TPixel](Stream stream)
   at ImageSharp.Formats.PngDecoder.Decode[TPixel](Configuration configuration, Stream stream, IDecoderOptions options)
   at ImageSharp.Image.Decode[TPixel](Stream stream, IDecoderOptions options, Configuration config)
   at ImageSharp.Image.Load[TPixel](Configuration config, Stream stream, IDecoderOptions options)
   at ImageSharp.Image.Load(Stream stream)`

### System Configuration

- ImageSharp version: 1.0.0-alpha7-00012
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): Windows 10 , VS 2017
- .NET Framework version: 1.2
- Additional information:

**Comment by JimBobSquarePants** [comment] 2017-04-27 03:11
@Drawaes When you have some time could you possibly have a look at this?

I've been trying to debug the issue for a couple of hours now to no avail. 

From what I can see the crc reading that is taking place within `ZlibInflateStream` is causing the private `currentDataRemaining` field in `DeframeStream` to be negative `-4`. Then, and I'm not sure how it's getting called `DeframeStream.Read(byte[] buffer, int offset, int count)` is called which throws our error.

**Comment by Drawaes** [comment] 2017-04-27 08:29
I think I know what the issue is without looking at it. But I would need
the exact test image.

**Comment by Drawaes** [comment] 2017-04-27 08:30
I am pretty sure I know how to fix it and it will make it faster at the same time.

**Comment by JimBobSquarePants** [comment] 2017-04-27 09:24
Wizzzzzzaaaard!

**Comment by Drawaes** [comment] 2017-04-27 18:45
Okay I have a fix for that bug, but it has highlighted another issue with the interlaced PNG. I will work on fixing that tonight.

**Comment by JimBobSquarePants** [comment] 2017-04-28 03:54
Fixed with #196

**Closed by JimBobSquarePants** 2017-04-28 03:54 UTC
Labels: area:formats, area:formats:png, bug

**Comment by srudenko** [comment] 2017-05-02 12:03
I can confirm that the issue has been fixed in 1.0.0-alpha8-00058. Tested using different types of images including the provided.,
