### ISSUE TITLE
Can't use ImageSharp.Drawing with VS 2017

### ISSUE THREAD

**Issue by agoretsky** [JimBobSquarePants/ImageSharp#190] opened 2017-04-26 16:21 UTC
### Description
Can't see and use ImageSharp.Drawing namespace and included members with VS 2017

### Steps to Reproduce
1) Create new console .NET Core app in VS 2017
2) Go to Manage NuGet Packages
3) Add new package source https://www.myget.org/F/imagesharp/api/v3/index.json and choose it
4) Check Include prerelease
5) Install ImageSharp
6) Install ImageSharp.Drawing
7) Go to Program.cs and type ImageSharp.Drawing
8) VS cannot see ImageSharp.Drawing namespace and all included members

**Comment by tocsoft** [comment] 2017-04-26 16:47
That's an issue I've seen too I'm sure its a bug in VS close and reopen VS and it'll show up in intellisense.  Definitely can't be an issue with our project as we are producing just a standard nuget package.

**Comment by lzcd** [comment] 2017-05-17 11:36
I've closed & reopened, cleaned and adjusted target runtimes numerous times... and all without success.
Whatever the problem is, I am unable to convince VS 2017 to utilise ImageSharp from a plain old .Net Core console app.

**Comment by JimBobSquarePants** [comment] 2017-05-17 14:26
@lzcd My money is a tooling thing. Is it ImageSharp or ImageSharp.Drawing?

I've been trying to find an old issue in the repo where I walked through testing install on different environments but for some reason I can't. 

I'll have a dig around. It might well be that we have to explicitly include packages we are not.

**Comment by lzcd** [comment] 2017-05-18 04:13
Previously I had success in being able to use one or both from within VS 2017 (after mucking around the with target package from memory)... but my most recent attempts only seem to gain intellisense on the overall namespace(s) and nothing else.

I'm curious what other people's experience is with creating a "vanilla"  .Net Core console app in VS 2017 and adding the ImageSharp nuget packages.

**Comment by Menighin** [comment] 2017-06-05 15:38
Having the same issue here, guys. Any news on that?

**Comment by Menighin** [comment] 2017-06-05 15:43
I tried closing and opening and it didn't work. I then reinstalled both packages and now it shows up (Y) 
Don't know what sorcery is that... Algo my VS is kind of out of date, maybe is also related...

**Comment by tocsoft** [comment] 2017-06-05 17:38
I would recommend you report the issue using the send feedback button from within visual studio. If you report the issue while its happening Microsoft will receive loads of extra telemetry to help them solve the issue. Its very much a Visual Studio issue because if you code anyway and do a build it'll build fine. 

We are just publishing/building a vanilla NuGet package, packaged using the dotnet cli so the the lack of intellisense can't be a bug introduced by us.

I'm closing this issue now as its outside of our control.

**Closed by tocsoft** 2017-06-05 17:38 UTC
