### ISSUE TITLE
there is no way to set TextAlignment in ImageExtensions.DrawText()

### ISSUE THREAD

**Issue by agoretsky** [JimBobSquarePants/ImageSharp#207] opened 2017-05-02 09:37 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
It looks like https://github.com/SixLabors/Fonts supports TextAlignment, but there is no way to pass this parameter through ImageSharp

### System Configuration

- ImageSharp version: 1.0.0-alpha8-00058
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version: .NET Core 1.0
- Additional information:

**Comment by tocsoft** [comment] 2017-05-02 10:23
haha... I literally added this to SixLabors.Fonts first thing this morning before heading out to work... I planned on exposing this in ImageSharp this evening.

Sharp eyes for spotting it.

**Comment by tocsoft** [comment] 2017-05-02 14:34
duplicate of #185

**Closed by tocsoft** 2017-05-02 14:34 UTC
Labels: area:drawing
